#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd -P)"
CLI="${AGENTIC_TEST_CLI:-$ROOT_DIR/agentic}"
VERSION="$(sed -n 's/^[[:space:]]*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$ROOT_DIR/package.json" | head -n 1)"
TMP_ROOT="$(mktemp -d /tmp/agentic-markers-e2e.XXXXXX)"
trap 'rm -rf "$TMP_ROOT"' EXIT

fail() {
  echo "[markers-e2e][FAIL] $1" >&2
  exit 1
}

assert_file_contains() {
  local path="$1"
  local needle="$2"
  grep -Fq -- "$needle" "$path" || fail "Expected '$needle' in $path"
}

assert_file_not_contains() {
  local path="$1"
  local needle="$2"
  if grep -Fq -- "$needle" "$path"; then
    fail "Did not expect '$needle' in $path"
  fi
}

FAKE_BIN="$TMP_ROOT/fake-bin"
mkdir -p "$FAKE_BIN"
for name in pip mempalace mempalace-mcp; do
  cat > "$FAKE_BIN/$name" <<'EOS'
#!/usr/bin/env bash
exit 0
EOS
  chmod +x "$FAKE_BIN/$name"
done

PROJECT="$TMP_ROOT/project"
HOME_DIR="$TMP_ROOT/home"
OUT1="$TMP_ROOT/install-1.log"
OUT2="$TMP_ROOT/install-2.log"
SNAPSHOT="$TMP_ROOT/snapshot.json"

COMMON_ENV=(
  "HOME=$HOME_DIR"
  "TMPDIR=$TMP_ROOT"
  "PATH=$FAKE_BIN:/usr/bin:/bin"
  "AGENTIC_DOCTOR=0"
  "AGENTIC_ENABLE_CONTEXT7=y"
  "AGENTIC_ENABLE_MEMPALACE=y"
  "CONTEXT7_API_KEY=test-context7-key"
)

run_install() {
  env "${COMMON_ENV[@]}" "$CLI" install \
    --project-dir "$PROJECT" \
    --agent-os opencode,codex,claude,cursor,gemini,kilocode,antigravity \
    --areas software \
    --specializations software.backend,software.general
}

echo "[markers-e2e] Scenario 1: generated markers include version and repository"
run_install >"$OUT1" 2>&1

assert_file_contains "$PROJECT/.opencode/AGENTS.md" "generated_by: agentic"
assert_file_contains "$PROJECT/.opencode/AGENTS.md" 'repository: "https://github.com/sawrus/agent-guides"'
assert_file_contains "$PROJECT/.opencode/AGENTS.md" "created_by: \"v$VERSION\""
assert_file_contains "$PROJECT/.opencode/AGENTS.md" "updated_by: \"v$VERSION\""
assert_file_contains "$PROJECT/.agentic.json" '"generated_by": "agentic"'
assert_file_contains "$PROJECT/.agentic.json" '"repository": "https://github.com/sawrus/agent-guides"'
assert_file_contains "$PROJECT/.agentic.json" "\"created_by\": \"v$VERSION\""
assert_file_contains "$PROJECT/.agentic.json" "\"updated_by\": \"v$VERSION\""
assert_file_contains "$OUT1" "=== Changelog v$VERSION ==="

echo "[markers-e2e] Scenario 2: schema-sensitive configs stay marker-free"
CONFIG_FILES=(
  "$PROJECT/opencode.json"
  "$PROJECT/.opencode/opencode.json"
  "$PROJECT/.mcp.json"
  "$PROJECT/.gemini/settings.json"
  "$PROJECT/.cursor/mcp.json"
  "$PROJECT/.kilocode/mcp.json"
  "$HOME_DIR/.gemini/antigravity/mcp_config.json"
  "$PROJECT/.codex/config.toml"
)

for file in "${CONFIG_FILES[@]}"; do
  [[ -f "$file" ]] || fail "Expected config file: $file"
  assert_file_not_contains "$file" "_agentic"
  assert_file_not_contains "$file" "generated_by"
  assert_file_not_contains "$file" "created_by"
  assert_file_not_contains "$file" "updated_by"
  assert_file_not_contains "$file" "Generated by agentic"
done

python3 - "${CONFIG_FILES[@]}" <<'PY'
import json
import sys
from pathlib import Path

for raw in sys.argv[1:-1]:
    json.loads(Path(raw).read_text(encoding="utf-8"))
codex = Path(sys.argv[-1]).read_text(encoding="utf-8")
if "[mcp_servers.context7]" not in codex or "[mcp_servers.mempalace]" not in codex:
    raise SystemExit("codex config missing expected MCP sections")
PY

echo "[markers-e2e] Scenario 3: identical second install does not rewrite project files"
python3 - "$PROJECT" "$SNAPSHOT" <<'PY'
import hashlib
import json
import os
import sys
from pathlib import Path

project = Path(sys.argv[1])
snapshot = Path(sys.argv[2])
data = {}
for path in sorted(p for p in project.rglob("*") if p.is_file()):
    rel = str(path.relative_to(project))
    stat = path.stat()
    data[rel] = {
        "hash": hashlib.sha256(path.read_bytes()).hexdigest(),
        "mtime_ns": stat.st_mtime_ns,
    }
snapshot.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
PY

sleep 1
run_install >"$OUT2" 2>&1

python3 - "$PROJECT" "$SNAPSHOT" <<'PY'
import hashlib
import json
import sys
from pathlib import Path

project = Path(sys.argv[1])
snapshot = json.loads(Path(sys.argv[2]).read_text(encoding="utf-8"))
current = {}
for path in sorted(p for p in project.rglob("*") if p.is_file()):
    rel = str(path.relative_to(project))
    stat = path.stat()
    current[rel] = {
        "hash": hashlib.sha256(path.read_bytes()).hexdigest(),
        "mtime_ns": stat.st_mtime_ns,
    }
if current != snapshot:
    changed = sorted(set(current) ^ set(snapshot))
    changed += sorted(k for k in current.keys() & snapshot.keys() if current[k] != snapshot[k])
    raise SystemExit("project files changed on identical second install: " + ", ".join(changed[:20]))
PY

echo 'markers e2e ok'
