//! AGENTS.md / MEMORY.md generation and destination-directory mapping.

use crate::app::App;
use crate::manifest::write_file_with_agentic_marker;
use crate::ui;
use std::path::{Path, PathBuf};

/// Destination directory for a bucket per agent OS ("-" means skip).
pub fn get_dest_dir(agent_os: &str, bucket: &str) -> String {
    let mapping: Option<[&str; 4]> = match agent_os {
        "opencode" => Some([
            ".opencode/rules",
            ".opencode/skills",
            ".opencode/commands",
            "-",
        ]),
        "cursor" => Some([".cursor/rules", ".cursor/skills", "-", "-"]),
        "kilocode" | "antigravity" => Some([
            ".kilocode/rules",
            ".kilocode/skills",
            ".kilocode/workflows",
            "-",
        ]),
        _ => None,
    };
    match mapping {
        Some(parts) => match bucket {
            "rules" => parts[0].to_string(),
            "skills" => parts[1].to_string(),
            "workflows" => parts[2].to_string(),
            "prompts" => parts[3].to_string(),
            _ => format!(".agent/{bucket}"),
        },
        None => format!(".agent/{bucket}"),
    }
}

fn build_header(app: &App) -> String {
    let rules_dir = get_dest_dir(&app.selected_agent_os[0], "rules");
    format!(
        "# Agentic Project Guidelines\n\nGenerated by {}.\n\n## Installation Context\n- Agent OS targets: {}\n- Primary agent rules directory: {}\n- Areas: {}\n- Specializations: {}\n\n---\n\n",
        crate::APP_NAME,
        app.selected_agent_os.join(" "),
        rules_dir,
        app.selected_areas.join(" "),
        app.selected_specs.join(" "),
    )
}

fn append_root_agents_template(app: &App, out: &mut String) {
    out.push_str("## Shared guidance\n\n");
    match app.kb.read_file("AGENTS.md") {
        Some(content) => out.push_str(&content),
        None => out.push_str("No root AGENTS.md template found.\n"),
    }
    out.push_str("\n---\n\n");
}

fn append_specialization_template(app: &App, out: &mut String, spec_key: &str) {
    let (area, spec) = spec_key.split_once('.').unwrap_or((spec_key, ""));
    out.push_str(&format!("## {area}/{spec}\n\n"));
    match app.kb.read_file(&format!("areas/{area}/{spec}/AGENTS.md")) {
        Some(content) => out.push_str(&content),
        None => out.push_str(&format!(
            "No specialization AGENTS.md template found for {spec_key}.\n"
        )),
    }
    out.push_str("\n---\n\n");
}

pub fn generate_agents_md(app: &mut App, project_dir: &Path) -> crate::Result<()> {
    let mut outputs: Vec<PathBuf> = Vec::new();
    if app.selected_agent_os_contains("opencode") {
        outputs.push(project_dir.join(".opencode/AGENTS.md"));
    }
    outputs.push(project_dir.join("AGENTS.md"));

    if app.dry_run {
        for out in &outputs {
            ui::log(app, &format!("DRY-RUN generate {}", out.display()));
            app.record_copied(&out.to_string_lossy());
        }
        return Ok(());
    }

    app.ensure_dir(project_dir);
    let mut content = build_header(app);
    append_root_agents_template(app, &mut content);
    for spec_key in app.selected_specs.clone() {
        append_specialization_template(app, &mut content, &spec_key);
    }
    for out in outputs {
        write_file_with_agentic_marker(app, &content, &out, "generated:AGENTS.md")?;
    }
    Ok(())
}

pub fn copy_memory_md(app: &mut App, project_dir: &Path) -> crate::Result<()> {
    let Some(src) = app.kb.read_file("MEMORY.md") else {
        ui::warn(app, "MEMORY.md not found in knowledge base; skipping");
        return Ok(());
    };
    let mut outputs: Vec<PathBuf> = Vec::new();
    if app.selected_agent_os_contains("opencode") {
        outputs.push(project_dir.join(".opencode/MEMORY.md"));
    }
    let needs_root = app.selected_agent_os.iter().any(|a| a != "opencode");
    if needs_root || !app.selected_agent_os_contains("opencode") {
        outputs.push(project_dir.join("MEMORY.md"));
    }
    for out in outputs {
        write_file_with_agentic_marker(app, &src, &out, "generated:MEMORY.md")?;
    }
    Ok(())
}

pub fn copy_review_pipeline(app: &mut App, project_dir: &Path) -> crate::Result<()> {
    let content = app
        .kb
        .read_file("REVIEW_PIPELINE.md")
        .ok_or("REVIEW_PIPELINE.md not found in knowledge base")?;
    write_file_with_agentic_marker(
        app,
        &content,
        &project_dir.join("REVIEW_PIPELINE.md"),
        "REVIEW_PIPELINE.md",
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dest_dir_mappings() {
        assert_eq!(get_dest_dir("opencode", "rules"), ".opencode/rules");
        assert_eq!(get_dest_dir("opencode", "workflows"), ".opencode/commands");
        assert_eq!(get_dest_dir("opencode", "prompts"), "-");
        assert_eq!(get_dest_dir("cursor", "skills"), ".cursor/skills");
        assert_eq!(get_dest_dir("cursor", "workflows"), "-");
        assert_eq!(get_dest_dir("kilocode", "workflows"), ".kilocode/workflows");
        assert_eq!(get_dest_dir("antigravity", "rules"), ".kilocode/rules");
        assert_eq!(get_dest_dir("default", "rules"), ".agent/rules");
        assert_eq!(get_dest_dir("codex", "prompts"), ".agent/prompts");
        assert_eq!(get_dest_dir("agents", "skills"), ".agent/skills");
    }

    fn test_app(project: &Path) -> App {
        let mut app = App::new().unwrap();
        app.project_dir = project.to_string_lossy().to_string();
        app.selected_agent_os = vec!["default".to_string()];
        app.selected_areas = vec!["software".to_string()];
        app.selected_specs = vec!["software.backend".to_string()];
        app
    }

    #[test]
    fn generates_agents_md_with_sections() {
        let tmp = tempfile::tempdir().unwrap();
        let mut app = test_app(tmp.path());
        generate_agents_md(&mut app, tmp.path()).unwrap();
        let content = std::fs::read_to_string(tmp.path().join("AGENTS.md")).unwrap();
        assert!(content.contains("# Agentic Project Guidelines"));
        assert!(content.contains("## Shared guidance"));
        assert!(content.contains("## software/backend"));
        assert!(content.starts_with("---\nagentic:\n"));
    }

    #[test]
    fn opencode_gets_extra_agents_md() {
        let tmp = tempfile::tempdir().unwrap();
        let mut app = test_app(tmp.path());
        app.selected_agent_os = vec!["opencode".to_string()];
        generate_agents_md(&mut app, tmp.path()).unwrap();
        assert!(tmp.path().join(".opencode/AGENTS.md").is_file());
        assert!(tmp.path().join("AGENTS.md").is_file());
    }

    #[test]
    fn memory_md_placement() {
        let tmp = tempfile::tempdir().unwrap();
        let mut app = test_app(tmp.path());
        app.selected_agent_os = vec!["opencode".to_string()];
        copy_memory_md(&mut app, tmp.path()).unwrap();
        assert!(tmp.path().join(".opencode/MEMORY.md").is_file());
        assert!(!tmp.path().join("MEMORY.md").exists());

        let tmp2 = tempfile::tempdir().unwrap();
        let mut app2 = test_app(tmp2.path());
        app2.selected_agent_os = vec!["opencode".to_string(), "codex".to_string()];
        copy_memory_md(&mut app2, tmp2.path()).unwrap();
        assert!(tmp2.path().join(".opencode/MEMORY.md").is_file());
        assert!(tmp2.path().join("MEMORY.md").is_file());
    }

    #[test]
    fn review_protocol_install_from_embedded_and_checkout() {
        for kb in [
            crate::kb::Kb::Embedded,
            crate::kb::Kb::Checkout(PathBuf::from(env!("CARGO_MANIFEST_DIR"))),
        ] {
            let tmp = tempfile::tempdir().unwrap();
            let mut app = test_app(tmp.path());
            app.kb = kb;
            copy_review_pipeline(&mut app, tmp.path()).unwrap();
            let content = std::fs::read_to_string(tmp.path().join("REVIEW_PIPELINE.md")).unwrap();
            assert!(content.starts_with("---\nagentic:\n"));
            assert!(content.contains("once per completed top-level task"));
            assert!(content.contains("Do not retry automatically"));
            assert_eq!(app.managed_records.len(), 1);
            assert_eq!(app.managed_records[0].source, "REVIEW_PIPELINE.md");
        }
    }

    #[test]
    fn review_protocol_dry_run_does_not_write() {
        let tmp = tempfile::tempdir().unwrap();
        let mut app = test_app(tmp.path());
        app.dry_run = true;
        copy_review_pipeline(&mut app, tmp.path()).unwrap();
        assert!(!tmp.path().join("REVIEW_PIPELINE.md").exists());
        assert!(app.managed_records.is_empty());
    }

    #[test]
    fn missing_review_protocol_is_reported() {
        let tmp = tempfile::tempdir().unwrap();
        let mut app = test_app(tmp.path());
        app.kb = crate::kb::Kb::Checkout(tmp.path().to_path_buf());
        let error = copy_review_pipeline(&mut app, tmp.path()).unwrap_err();
        assert!(error.to_string().contains("REVIEW_PIPELINE.md not found"));
    }

    #[test]
    fn unknown_spec_yields_placeholder() {
        let tmp = tempfile::tempdir().unwrap();
        let mut app = test_app(tmp.path());
        app.selected_specs = vec!["software.backend".into(), "software.ghost".into()];
        generate_agents_md(&mut app, tmp.path()).unwrap();
        let content = std::fs::read_to_string(tmp.path().join("AGENTS.md")).unwrap();
        assert!(content.contains("No specialization AGENTS.md template found for software.ghost."));
    }
}
