//! Generated-file marker injection, mirroring the Python heredocs of the bash
//! version byte-for-byte for markdown/JSON/comment-prefixed outputs.

use serde_json::Value;

/// Pretty JSON with 2-space indent and trailing newline
/// (equivalent to Python `json.dumps(data, indent=2, ensure_ascii=False) + "\n"`).
pub fn to_pretty_json(data: &Value) -> String {
    let mut out = serde_json::to_string_pretty(data).unwrap_or_else(|_| "{}".to_string());
    out.push('\n');
    out
}

fn yaml_quote(value: &str) -> String {
    serde_json::to_string(value).unwrap_or_else(|_| format!("\"{value}\""))
}

/// Extract `created_by` from an existing destination file, defaulting to the
/// current version label.
fn existing_created_by(existing: Option<&str>, version: &str) -> String {
    let Some(old) = existing else {
        return version.to_string();
    };
    for line in old.lines() {
        if let Some(rest) = line.strip_prefix("  created_by:") {
            let value = rest.trim();
            if !value.is_empty() {
                return value.trim_matches('"').to_string();
            }
        }
    }
    version.to_string()
}

fn markdown_with_marker(
    body: &str,
    source_ref: &str,
    repo: &str,
    version: &str,
    existing_dest: Option<&str>,
) -> String {
    let created_by = existing_created_by(existing_dest, version);
    let block = format!(
        "agentic:\n  generated_by: agentic\n  source: {}\n  repository: {}\n  created_by: {}\n  updated_by: {}\n",
        yaml_quote(source_ref),
        yaml_quote(repo),
        yaml_quote(&created_by),
        yaml_quote(version),
    );
    if let Some(rest) = body.strip_prefix("---\n") {
        if let Some(end) = rest.find("\n---") {
            let end = end + 4;
            return format!("{}{}{}", &body[..end + 1], block, &body[end + 1..]);
        }
    }
    format!("---\n{block}---\n{body}")
}

fn commented(body: &str, prefix: &str, source_ref: &str, repo: &str) -> String {
    let marker = format!("Generated by agentic; source: {source_ref}; repository: {repo}");
    let line = format!("{prefix} {marker}\n");
    if body.starts_with("#!") {
        if let Some(newline) = body.find('\n') {
            let (first, rest) = body.split_at(newline + 1);
            return format!("{first}{line}{rest}");
        }
    }
    format!("{line}{body}")
}

/// Apply the agentic marker transformation based on the destination suffix.
/// `existing_dest` is the current destination content used to preserve
/// `created_by` in markdown frontmatter.
pub fn add_marker(
    text: &str,
    dest_name: &str,
    source_ref: &str,
    repo: &str,
    version: &str,
    existing_dest: Option<&str>,
) -> Result<String, String> {
    let suffix = dest_name
        .rsplit_once('.')
        .map(|(_, ext)| ext.to_lowercase())
        .unwrap_or_default();
    match suffix.as_str() {
        "md" => Ok(markdown_with_marker(
            text,
            source_ref,
            repo,
            version,
            existing_dest,
        )),
        "json" => {
            let data: Value = serde_json::from_str(text)
                .map_err(|e| format!("Cannot parse JSON for {dest_name}: {e}"))?;
            if !data.is_object() {
                return Err(format!(
                    "Cannot add agentic metadata to non-object JSON: {dest_name}"
                ));
            }
            Ok(to_pretty_json(&data))
        }
        "ts" | "tsx" | "js" | "jsx" | "css" => Ok(commented(text, "//", source_ref, repo)),
        _ => Ok(commented(text, "#", source_ref, repo)),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const REPO: &str = "https://github.com/sawrus/agent-guides";

    #[test]
    fn markdown_without_frontmatter_gets_new_block() {
        let out = add_marker("# Title\n", "a.md", "areas/x/a.md", REPO, "v1.0.0", None).unwrap();
        assert!(out.starts_with("---\nagentic:\n  generated_by: agentic\n"));
        assert!(out.contains("  source: \"areas/x/a.md\"\n"));
        assert!(out.ends_with("---\n# Title\n"));
    }

    #[test]
    fn markdown_with_frontmatter_injects_into_existing() {
        let body = "---\ntitle: x\n---\nbody\n";
        let out = add_marker(body, "a.md", "src", REPO, "v1.0.0", None).unwrap();
        assert!(out.starts_with("---\ntitle: x\nagentic:\n"));
        assert!(out.contains("\n---\nbody\n"));
    }

    #[test]
    fn markdown_preserves_created_by_from_existing_dest() {
        let existing =
            "---\nagentic:\n  generated_by: agentic\n  created_by: \"v0.5.0\"\n---\nold\n";
        let out = add_marker("new\n", "a.md", "src", REPO, "v1.0.0", Some(existing)).unwrap();
        assert!(out.contains("  created_by: \"v0.5.0\"\n"));
        assert!(out.contains("  updated_by: \"v1.0.0\"\n"));
    }

    #[test]
    fn json_object_reserialized_pretty() {
        let out = add_marker("{\"b\":1,\"a\":2}", "x.json", "src", REPO, "v1", None).unwrap();
        assert_eq!(out, "{\n  \"b\": 1,\n  \"a\": 2\n}\n");
    }

    #[test]
    fn json_non_object_rejected() {
        assert!(add_marker("[1,2]", "x.json", "src", REPO, "v1", None).is_err());
        assert!(add_marker("not json", "x.json", "src", REPO, "v1", None).is_err());
    }

    #[test]
    fn ts_and_sh_comment_prefixes() {
        let ts = add_marker("code();\n", "x.ts", "src", REPO, "v1", None).unwrap();
        assert!(ts.starts_with("// Generated by agentic; source: src; repository:"));
        let sh = add_marker("echo hi\n", "x.sh", "src", REPO, "v1", None).unwrap();
        assert!(sh.starts_with("# Generated by agentic; source: src;"));
        let other = add_marker("x\n", "noext", "src", REPO, "v1", None).unwrap();
        assert!(other.starts_with("# Generated by agentic;"));
    }

    #[test]
    fn shebang_preserved_first() {
        let out = add_marker("#!/bin/sh\necho hi\n", "x.sh", "src", REPO, "v1", None).unwrap();
        assert!(out.starts_with("#!/bin/sh\n# Generated by agentic;"));
    }

    #[test]
    fn marker_is_idempotent_for_markdown() {
        let first = add_marker("# T\n", "a.md", "s", REPO, "v1", None).unwrap();
        // Re-adding a marker to source content again produces the same output
        let second = add_marker("# T\n", "a.md", "s", REPO, "v1", Some(&first)).unwrap();
        assert_eq!(first, second);
    }
}
