//! Inventory and positive ownership evidence for project reconciliation.
use crate::project_update::BASELINES;
use serde_json::{json, Value};
use std::collections::BTreeMap;
use std::path::{Component, Path, PathBuf};

const ROOT_FILES: &[&str] = &[
    "AGENTS.md",
    "MEMORY.md",
    "REVIEW_PIPELINE.md",
    ".agentic.json",
    ".mcp.json",
    "opencode.json",
    ".mempalaceignore",
];
const ROOT_DIRS: &[&str] = &[
    ".agent",
    ".opencode",
    ".codex",
    ".claude",
    ".cursor",
    ".kilocode",
    ".gemini",
    ".antigravity",
    BASELINES,
];

pub fn safe_path(root: &Path, rel: &str) -> crate::Result<PathBuf> {
    let path = Path::new(rel);
    if path.as_os_str().is_empty()
        || path
            .components()
            .any(|c| !matches!(c, Component::Normal(_)))
    {
        return Err(format!("Unsafe project path: {rel}").into());
    }
    let mut joined = root.to_path_buf();
    for part in path.components() {
        joined.push(part);
        match std::fs::symlink_metadata(&joined) {
            Ok(meta) if meta.file_type().is_symlink() => {
                return Err(format!("Symlink project path: {rel}").into())
            }
            Ok(_) => {}
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(e) => return Err(e.into()),
        }
    }
    Ok(joined)
}

pub fn recognized(text: &str) -> bool {
    // Require metadata in the header, not a mention somewhere in a user's prose.
    let header: String = text.lines().take(20).collect::<Vec<_>>().join("\n");
    (text.starts_with("---\n")
        && header.contains("agentic:")
        && header.contains("generated_by: agentic")
        && header.contains(crate::APP_REPO_LINK))
        || header.lines().take(2).any(|l| {
            (l.starts_with('#') || l.starts_with("//"))
                && l.contains("Generated by agentic; source:")
                && l.contains(crate::APP_REPO_LINK)
        })
        || text.starts_with("# Agentic Project Guidelines\n\nGenerated by agentic.")
        || serde_json::from_str::<Value>(text).ok().is_some_and(|v| {
            v["_agentic"]["generated_by"] == "agentic"
                && v["_agentic"]["repository"] == crate::APP_REPO_LINK
        })
}

fn collect(root: &Path, rel: &str, files: &mut BTreeMap<String, Vec<u8>>) -> crate::Result<()> {
    let path = safe_path(root, rel)?;
    if path.is_dir() {
        for entry in std::fs::read_dir(&path)? {
            let entry = entry?;
            collect(
                root,
                &format!("{rel}/{}", entry.file_name().to_string_lossy()),
                files,
            )?;
        }
    } else if path.is_file() {
        files.insert(rel.into(), std::fs::read(path)?);
    }
    Ok(())
}

pub fn inventory(root: &Path) -> crate::Result<BTreeMap<String, Vec<u8>>> {
    let mut files = BTreeMap::new();
    for rel in ROOT_FILES.iter().chain(ROOT_DIRS) {
        collect(root, rel, &mut files)?;
    }
    // Dynamic extensions also use project-local dot directories.
    for entry in std::fs::read_dir(root)? {
        let entry = entry?;
        let name = entry.file_name().to_string_lossy().to_string();
        if name.starts_with('.')
            && !matches!(name.as_str(), ".git" | ".agentic-backups" | ".agentic")
            && entry.file_type()?.is_dir()
        {
            // Scan only agent directories named by the manifest, never caches/venvs.
            let data: Value = files
                .get(crate::PROJECT_MANIFEST_NAME)
                .and_then(|v| serde_json::from_slice(v).ok())
                .unwrap_or(Value::Null);
            if data["settings"]["agent_os"].as_array().is_some_and(|a| {
                a.iter()
                    .any(|v| v.as_str().is_some_and(|s| name == format!(".{s}")))
            }) {
                collect(root, &name, &mut files)?;
            }
        }
    }
    let data: Value = files
        .get(crate::PROJECT_MANIFEST_NAME)
        .and_then(|v| serde_json::from_slice(v).ok())
        .unwrap_or(Value::Null);
    for item in data["managed_files"].as_array().into_iter().flatten() {
        if let Some(rel) = item["path"].as_str() {
            if Path::new(rel).is_absolute() && item["marker"] == "config" {
                continue;
            }
            if rel.starts_with(".agentic-backups/") || rel.starts_with(".git/") {
                return Err(format!("Protected manifest path: {rel}").into());
            }
            collect(root, rel, &mut files)?;
        }
    }
    Ok(files)
}

pub fn owned_files(files: &BTreeMap<String, Vec<u8>>, data: &Value) -> BTreeMap<String, Value> {
    let mut owned = BTreeMap::new();
    for item in data["managed_files"].as_array().into_iter().flatten() {
        if let Some(rel) = item["path"].as_str().filter(|r| Path::new(r).is_relative()) {
            owned.insert(rel.into(), item.clone());
        }
    }
    for (rel, bytes) in files {
        if rel == crate::PROJECT_MANIFEST_NAME || rel.starts_with(BASELINES) {
            continue;
        }
        if std::str::from_utf8(bytes).ok().is_some_and(recognized) {
            owned.entry(rel.clone()).or_insert(json!({"path": rel}));
        }
    }
    owned
}
